# Basic
title: Jesse Style
subtitle: 杰西风格
welcome_message: 把每一件简单的事情做好，就是不简单.把每一件平凡的事情做好，就是不平凡.<br>Every one simple thing, is not simple.To do each common thing, is not trivial.
description: 态度决定一切，细节决定成败。<br>Attitude decides everything, details determine success or failure.
creator:

url: "https://jessestyle.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

-nav:
 -    - {title: Projects, description: My Projects, url: 'https://jessestyle.github.io'}
 -    # - {title: Another Button, description: A button, url: 'http://example.com'}
 -  

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: 
    twitter: 
    gplus: 
    mail: JesseStyle@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
